CREATE TABLE Engineer(
	Name Varchar(50),
	Phone INT,
	ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	Specialty INT,
	Identification INT ,
	PRIMARY KEY (ID)
)
CREATE TABLE Specialty(
	ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	Description VARCHAR(50),
	UNIQUE(ID)
)
CREATE TABLE Client(
	Name VarChar(50),
	Phone INT,
	Identification INT NOT NULL,
	UserName VarChar(50) NOT NULL,
	UNIQUE(UserName),
	PRIMARY KEY(UserName)
)
CREATE TABLE Employee(
	Name Varchar(50),
	Identification INT NOT NULL,
	Phone INT,
	HourPrice INT,
	Proyect INT,
	ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	PRIMARY KEY (ID)
)
CREATE TABLE Materials(
	Name Varchar(50),
	ID INT GENERATED ALWAYS AS IDENTITY NOT NULL ,
	UnitPrice INT,
	PRIMARY KEY(ID)
)

CREATE TABLE Stage(
	ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	Description VARCHAR(50),
	PRIMARY KEY (ID)
)
CREATE TABLE Build(
	Name VARCHAR(50),
	location INT,
	Rooms INT,
	Bathroms INT,
	Floor INT,
	GroundSize INT,
	BuildSize INT,
	Owner VARCHAR(50),
	Proyect INT,
	ID INT GENERATED ALWAYS AS IDENTITY NOT NULL ,
	Materials INT,
	PRIMARY KEY(ID)
)
CREATE TABLE Proyect(
	ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	Employee INT,
	Hours INT,
	StageID INT,
	Stage VARCHAR(50),
	Begin DATE,
	ENDS DATE,
	PRIMARY KEY(ID)
)

CREATE TABLE MaterialRegistry(
	Price INT,
	Quantity INT,
	Material INT,
	Build INT,
	Name VARCHAR(50),
	Stage INT,
	ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	Primary KEY (ID)
)
CREATE TABLE Bills(
	Materials INT,
	Photo VARCHAR(200),
	Number INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	Proyect INT,
	Total INT,
	Provider VARCHAR(50),
	PRIMARY KEY(Number)
)

CREATE TABLE Location(
	Province VARCHAR(50),
	District VARCHAR(50),
	Canton VARCHAR(50),
	ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	PRIMARY KEY (ID)
)